### ISSUE TITLE
Intermittently getting the error CypressError: `cy.task('cypress-cucumber-preprocessor:test-step-finished')` timed out after waiting `60000ms`

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1040]
### Current behavior

On GitLabCI, when the tests are running continuously by the pipeline, it is failing very often. The error which I can see Intermittently getting the error CypressError: `cy.task('cypress-cucumber-preprocessor:test-step-finished')` timed out after waiting `60000ms`.  Also, it didn't generate the multiple-cucumber report due to this error.

```
An error was thrown in your plugins file while executing the handler for the after:run event.
The error we received was:
TypeError: Cannot destructure property 'message' of 'testStepResult' as it is undefined.
    at JsonFormatter.getStepData (/builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:183:17)
    at /builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:100:33
    at Array.map (<anonymous>:null:null)
    at /builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:98:66
    at Array.map (<anonymous>:null:null)
    at /builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:94:36
    at Array.map (<anonymous>:null:null)
    at JsonFormatter.onTestRunFinished (/builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:87:63)
    at EventEmitter.<anonymous> (/builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/formatter/json_formatter.js:43:22)
    at EventEmitter.emit (node:events:525:35)
    at afterRunHandler (/builds/cloud/custom-software/nimbus-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js:134:30)
```

### Desired behaviour

The test should work without any further issues and reports has to be generated.

### Versions

* **Cypress version**: 12.14.0
* **Preprocessor version**: 18.0.1
* **Node version**: v19.9.0

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by rakeshnambiar** [comment]
@badeball that is very difficult as I cannot share the original application details here. Let me see if I can reproduce it on any other public website :(

**Comment by andriand06** [comment]
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/64359593/0ce6eb17-58ea-4358-b9ae-4e2cc9a407b2)
Hi, i also have the same issue when github action running the jobs. also we can reproduce the issue by running npx cypress run --env someEnvVariable --browser {chrome, edge}

**Comment by badeball** [comment]
Feel free to provide me with an example any time soon.

**Comment by youvegotnigel** [comment]
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/48122863/1cd27978-23a8-44b8-9c02-33fd89370f49)

I am also facing this issue, after upgrading to version '^17.2.0' of cypress-cucumber-preprocessor. This is the error I got in the Jenkins console.

`An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

TypeError: Cannot destructure property 'message' of 'testStepResult' as it is undefined.
    at JsonFormatter.getStepData (C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@cucumber\cucumber\src\formatter\json_formatter.ts:281:13)
    at C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@cucumber\cucumber\src\formatter\json_formatter.ts:161:23
    at Array.map (<anonymous>)
    at C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@cucumber\cucumber\src\formatter\json_formatter.ts:159:58
    at Array.map (<anonymous>)
    at C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@cucumber\cucumber\src\formatter\json_formatter.ts:155:30
    at Array.map (<anonymous>)
    at JsonFormatter.onTestRunFinished (C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@cucumber\cucumber\src\formatter\json_formatter.ts:147:59)
    at EventEmitter.<anonymous> (C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@cucumber\cucumber\src\formatter\json_formatter.ts:92:14)
    at EventEmitter.emit (node:events:525:35)
    at EventEmitter.emit (node:domain:489:12)
    at afterRunHandler (C:\jenkins\workspace\S12\S12_Regression_Tests\node_modules\@badeball\cypress-cucumber-preprocessor\dist\plugin-event-handlers.js:146:30)`

Cypress version: 11.2.0
Node version: v18.16.0

**Comment by badeball** [comment]
I want to remind readers that the _only_ thing I want, is a way to reproduce the issue.

@youvegotnigel, you mention a _version range_ (`^17.2.0`), which doesn't really help me. More useful would be to tell me exactly which version that introduces the erroneous behavior.

**Comment by badeball** [comment]
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.
