### ISSUE TITLE
`> Unexpected state in testCaseStartedHandler: step-started` on version `18.0.4`

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1074]
### Current behavior

Unexpected error and tests are skipping

```
CypressError: `cy.task('cypress-cucumber-preprocessor:test-case-started')` failed with the following error:
[469](https://masked/-/jobs/4903688188#L469)> Unexpected state in testCaseStartedHandler: step-started (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
[470](https://masked/-/jobs/4903688188#L470)https://on.cypress.io/api/task
[471](https://masked/-/jobs/4903688188#L471)      at <unknown> ([https://myapp.com/__cypress/runner/cypress_runner.js:151215:78](https://xx/__cypress/runner/cypress_runner.js:151215:78))
[472](https://masked/-/jobs/4903688188#L472)      at tryCatcher ([https://myapp.com/__cypress/runner/cypress_runner.js:18744:23](https://xx/__cypress/runner/cypress_runner.js:18744:23))
[473](https://xx/-/jobs/4903688188#L473)      at Promise._settlePromiseFromHandler ([https://myapp.com/__cypress/runner/cypress_runner.js:16679:31](https://xxp/__cypress/runner/cypress_runner.js:16679:31))
[474](https://xx/-/jobs/4903688188#L474)      at Promise._settlePromise ([https://myapp.com/__cypress/runner/cypress_runner.js:16736:18](https://xx__cypress/runner/cypress_runner.js:16736:18))
[475](https://xx/-/jobs/4903688188#L475)      at Promise._settlePromise0 ([https://myapp.com/__cypress/runner/cypress_runner.js:16781:10](https://xx/__cypress/runner/cypress_runner.js:16781:10))
[476](https://xx/-/jobs/4903688188#L476)      at Promise._settlePromises ([https://myapp.com/__cypress/runner/cypress_runner.js:16857:18](https://masked/__cypress/runner/cypress_runner.js:16857:18))
[477](https://masked/-/jobs/4903688188#L477)      at _drainQueueStep ([https://myapp.com/__cypress/runner/cypress_runner.js:13451:12](https://masked/__cypress/runner/cypress_runner.js:13451:12))
[478](https://masked/-/jobs/4903688188#L478)      at _drainQueue ([https://myapp.com/__cypress/runner/cypress_runner.js:13444:9](https://masked/__cypress/runner/cypress_runner.js:13444:9))
[479](https://masked/-/jobs/4903688188#L479)      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues ([https://myapp.com/__cypress/runner/cypress_runner.js:13460:5](https://masked/__cypress/runner/cypress_runner.js:13460:5))
[480](https://masked/-/jobs/4903688188#L480)      at Async.drainQueues ([https://myapp.com/__cypress/runner/cypress_runner.js:13330:14](https://masked/__cypress/runner/cypress_runner.js:13330:14))
[481](https://masked/-/jobs/4903688188#L481)  From Your Spec Code:
[482](https://masked/-/jobs/4903688188#L482)      at taskTestCaseStarted (node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:75:0)
[483](https://masked/-/jobs/4903688188#L483)      at Context.eval (node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:247:0)
[484](https://masked/-/jobs/4903688188#L484)  
[485](https://masked/-/jobs/4903688188#L485)  From Node.js Internals:
[486](https://masked/-/jobs/4903688188#L486)    Error: Unexpected state in testCaseStartedHandler: step-started (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
[487](https://masked/-/jobs/4903688188#L487)        at createError (/builds/mycompany/cloud/custom-software/myapp-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/error.js:9:12)
[488](https://masked/-/jobs/4903688188#L488)        at testCaseStartedHandler (/builds/mycompany/cloud/custom-software/myapp-test-suite/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js:325:43)
[489](https://masked/-/jobs/4903688188#L489)        at invoke (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:246:16)
[490](https://masked/-/jobs/4903688188#L490)        at <unknown> (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:59:14)
[491](https://masked/-/jobs/4903688188#L491)        at tryCatcher (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
[492](https://masked/-/jobs/4903688188#L492)        at Function.Promise.attempt.Promise.try (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29)
[493](https://masked/-/jobs/4903688188#L493)        at Object.wrapChildPromise (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
[494](https://masked/-/jobs/4903688188#L494)        at RunPlugins.taskExecute (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:252:10)
[495](https://masked/-/jobs/4903688188#L495)        at RunPlugins.execute (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:166:21)
[496](https://masked/-/jobs/4903688188#L496)        at EventEmitter.<anonymous> (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:56:12)
[497](https://masked/-/jobs/4903688188#L497)        at EventEmitter.emit (node:events:513:28)
[498](https://masked/-/jobs/4903688188#L498)        at process.<anonymous> (/root/.cache/Cypress/12.17.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
[499](https://masked/-/jobs/4903688188#L499)        at process.emit (node:events:513:28)
[500](https://masked/-/jobs/4903688188#L500)        at emit (node:internal/child_process:944:14)
[501](https://masked/-/jobs/4903688188#L501)        at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Test code to reproduce

this is not happening for all the test suites and repeatedly happening for one of the batches. So I cannot share this suite publicly. Let me check how this batch is different from the remaining

### Versions

* **Cypress version**: 12.17.1
* **Preprocessor version**: 18.0.4
* **Node version**: v20.5.1

**Comment by rakeshnambiar** [comment]
I can confirm that this is happening when I have the scenario like:

```
    Then I should able to see the below labels displayed on the screen
      | A | B | C | D | E | F | G |
 ```     
```javascript
Then('I should able to see the below labels displayed on the page', (dataTable) => {

})
```
this was working fine on version `16.0.0` but after I migrated to version `18.0.4` this error started appearing.

**Comment by badeball** [comment]
Lmao, you fucking donkey. Why cant you just fill out the template like a normal person?

**Comment by rakeshnambiar** [comment]
@badeball Is this the way you are collaborating with others? Really shame and mind your language. 

I filled the template with the details I can share with. Some of the information doesn't applicable to me like a sample repo when I initially reported the issue as I am not very clear about the scenario.

**Comment by rakeshnambiar** [comment]
I would also remind you the GitHub community guideliness and code of conduct as I don't want to use the same language you hv used here.

[GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#:~:text=Be%20welcoming%20and%20open%2Dminded,and%20those%20just%20getting%20started.)
[GitHub Docshttps://docs.github.com › site-policyGitHub Community Code of Conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct)

![IMG_6524](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20258636/aa0e218e-60eb-415f-aa6d-ac67b9330b54)

**Comment by rakeshnambiar** [comment]
N/A

**Comment by rakeshnambiar** [comment]
@lgandecki I would like to bring your attention to this abusing comment as you are one of the main collaborator here. Thanks

**Comment by badeball** [comment]
Closing as not reproducible. Feel free to open up another issue if anything changes in this regard.
