### ISSUE TITLE
diagnostics - Cypress.env is not a function when referring to env object as const

### ISSUE THREAD

**Issue by jessica-jorgenson** [badeball/cypress-cucumber-preprocessor#1120]
### Current behavior

Upon running `npx cypress-cucumber-diagnostics`, I am met with the error:
```
TypeError: Cypress.env is not a function
    at cypress/support/appOne/pages.ts (C:\Users\JessicaJorgenson\Repos\CypressExample\.output-7bedd1.cjs:15748:22)
    at __init (C:\Users\JessicaJorgenson\Repos\CypressExample\.output-7bedd1.cjs:10:58)
    at cypress/support/appOne/step-definitions/preconditions.steps.ts (C:\Users\JessicaJorgenson\Repos\CypressExample\.output-7bedd1.cjs:15762:7)
    at __init (C:\Users\JessicaJorgenson\Repos\CypressExample\.output-7bedd1.cjs:10:58)
    at C:\Users\JessicaJorgenson\Repos\CypressExample\.output-7bedd1.cjs:15770:3
    at Object.<anonymous> (C:\Users\JessicaJorgenson\Repos\CypressExample\.output-7bedd1.cjs:15771:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
Error: Failed to evaluate step definitions, with errors shown above...
    at C:\Users\JessicaJorgenson\Repos\CypressExample\node_modules\@badeball\cypress-cucumber-preprocessor\dist\diagnostics\diagnose.js:110:27
    at withRegistry (C:\Users\JessicaJorgenson\Repos\CypressExample\node_modules\@badeball\cypress-cucumber-preprocessor\dist\registry.js:188:5)
    at diagnose (C:\Users\JessicaJorgenson\Repos\CypressExample\node_modules\@badeball\cypress-cucumber-preprocessor\dist\diagnostics\diagnose.js:103:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (C:\Users\JessicaJorgenson\Repos\CypressExample\node_modules\@badeball\cypress-cucumber-preprocessor\dist\diagnostics\index.js:189:20)
```
When I have a constant equal to a Cypress.env value.
See here: https://github.com/jessica-jorgenson/cucumber-preprocessor-error/blob/main/cypress/support/appOne/pages.ts

When referring to the env like so: `return Cypress.env("urls").main.replace("bing", "google")`, the error doesn't occur.

### Desired behavior

Cypress behaves as usual, so this shouldn't raise an error on cypress-cucumber-preprocessor...riiight?

### Test code to reproduce

Repo: https://github.com/jessica-jorgenson/cucumber-preprocessor-error

### Versions

* **Cypress version**:  ^13.3.0
* **Preprocessor version**: ^19.0.1
* **Node version**: 18.18.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Cypress behaves as usual, so this shouldn't raise an error on cypress-cucumber-preprocessor...riiight?

That'd be nice, but it's not quite the case. The steps are evaluated in a non-cypress environment and these variables aren't available. This is a result of careful consideration between evaluation and static analysis. For now, you need to move invocation of Cypress function inside methods and away from global scope. I will update the documentation to further explain this, in time.

**Comment by jessica-jorgenson** [comment]
Thank you!

**Comment by badeball** [comment]
I found that I previously actually did make attempts at [mocking](https://github.com/badeball/cypress-cucumber-preprocessor/blob/v19.1.0/lib/diagnostics/diagnose.ts#L165) Cypress global during evaluation. Thus, I've improved that behavior slightly with v19.1.1 and your original code should now hopefully run fine.

**Comment by jessica-jorgenson** [comment]
Oh thank you for working on this! It's definitely a step in the right direction, but it seems it's still having a hard time with the new update. Is it something else I'm doing wrong?
```
TypeError: Cannot read properties of undefined (reading 'main')
    at cypress/support/appOne/pages.ts (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/.output-9565d5.cjs:15748:33)
    at __init (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/.output-9565d5.cjs:10:58)
    at cypress/support/appOne/step-definitions/preconditions.steps.ts (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/.output-9565d5.cjs:15762:7)
    at __init (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/.output-9565d5.cjs:10:58)
    at /Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/.output-9565d5.cjs:15770:3
    at Object.<anonymous> (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/.output-9565d5.cjs:15771:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
Error: Failed to evaluate step definitions, with errors shown above...
    at /Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/node_modules/@badeball/cypress-cucumber-preprocessor/dist/diagnostics/diagnose.js:117:27
    at withRegistry (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/node_modules/@badeball/cypress-cucumber-preprocessor/dist/registry.js:188:5)
    at diagnose (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/node_modules/@badeball/cypress-cucumber-preprocessor/dist/diagnostics/diagnose.js:111:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (/Users/jessicajorgenson/Documents/GitHub/cucumber-preprocessor-error/node_modules/@badeball/cypress-cucumber-preprocessor/dist/diagnostics/index.js:189:20)
```

**Comment by badeball** [comment]
Ah, the return value of mocked functions is just undefined, which means that accessing the value as an object isn't going to work. Doing something about this is out of scope for this project as of now.

**Comment by mrkjdy** [comment]
I also have this problem. It would be awesome if this was fixed! Is it possible to run the diagnostics script within a Cypress environment so that it doesn't need to be mocked? Maybe the diagnostics code could be ran as a Cypress test?

I'd really like to use this tool without needing to change my code.

**Comment by badeball** [comment]
> Maybe the diagnostics code could be ran as a Cypress test?

This is not something I'm considering right now. I am however open to introducing static analysis with fallback, ref. https://github.com/badeball/cypress-cucumber-preprocessor/issues/1129.

**Comment by badeball** [comment]
Dry run has been completely overhauled with v21.0.0 and changed in regards to the original issue.
