### ISSUE TITLE
the tests tab on Azure devops pipeline report an issue with cypress cucumber preprocessor

### ISSUE THREAD

**Issue by parseh122** [badeball/cypress-cucumber-preprocessor#1164]
### Current behavior

From Node.js Internals:
  TypeError: state.messages.current.findLastIndex is not a function
      at testCaseStartedHandler (C:\agent\vsts-agent-win-x64-2.175.2\_work\1391\s\node_modules\@badeball\cypress-cucumber-preprocessor\dist\plugin-event-handlers.js:390:69)
      at invoke (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:248:16)
      at <unknown> (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:59:14)
      at tryCatcher (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\bluebird\js\release\util.js:16:23)
      at Function.Promise.attempt.Promise.try (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\bluebird\js\release\method.js:39:29)
      at Object.wrapChildPromise (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:58:23)
      at RunPlugins.taskExecute (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:254:10)
      at RunPlugins.execute (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:166:21)
      at EventEmitter.<anonymous> (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:56:12)
      at EventEmitter.emit (node:events:513:28)
      at EventEmitter.emit (node:domain:489:12)
      at process.<anonymous> (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
      at process.emit (node:events:513:28)
      at process.emit (node:domain:489:12)
      at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Cypress\Cache\13.6.6\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
      at emit (node:internal/child_process:946:14)
      at processTicksAndRejections (node:internal/process/task_queues:84:21)]]></failure>
    </testcase>
    <testcase name="INV - API error handling for document uploads on Save (Integration) - PHX-1622 &quot;after each&quot; hook for &quot;PHX-1622.1 This scenario will test that if the portal api returns a non-success response then the order details are saved (example #1)&quot;" time="0.000" classname="&quot;after each&quot; hook for &quot;PHX-1622.1 This scenario will test that if the portal api returns a non-success response then the order details are saved (example #1)&quot;">
      <failure message="Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `INV - API error handling fo...`" type="Error"><![CDATA[Error: Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite: `INV - API error handling fo...`
    at createError (https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:8021:16)
    at fail (https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:8073:39)
    at assert (https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:8080:9)
    at assertAndReturn (https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:8084:9)
    at Context.afterEachHandler (https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:15207:85)
    at Context.eval ([https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:14843:30)]]></failure>](https://testing-yprimelogin.eclinicalcloud.net/__cypress/tests?p=cypress\e2e\orders\api-error-handling-upon-save-I\api-error-handling-upon-save-I.feature:14843:30)]]%3E%3C/failure%3E)
    </testcase>
  </testsuite>
</testsuites>
An error was thrown in your plugins file while executing the handler for the after:spec event.

The error we received was:

Error: Unexpected state in afterSpecHandler: has-reloaded-received-envelopes (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
    at createError (C:\agent\vsts-agent-win-x64-2.175.2\_work\1391\s\node_modules\@badeball\cypress-cucumber-preprocessor\dist\helpers\error.js:9:12)
    at afterSpecHandler (C:\agent\vsts-agent-win-x64-2.175.2\_work\1391\s\node_modules\@badeball\cypress-cucumber-preprocessor\dist\plugin-event-handlers.js:276:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Desired behavior
No extra tests to be reported with "after each" hook issue telling Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)  Because this error occurred during a after each hook we are skipping the remaining tests in the current suite: - API error handling fo...

### Versions

* **Cypress version**: "cypress": "^13.6.4",
* **Preprocessor version**:"@badeball/cypress-cucumber-preprocessor": "^20.0.1",
* **Node version**:"ts-node": "~8.3.0",  "@babel/node": "^7.12.16",node --version
v21.6.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md
