### ISSUE TITLE
cy.origin() failed to run the callback function due to the following error:

### ISSUE THREAD

**Issue by EduardoZirbell** [badeball/cypress-cucumber-preprocessor#1228]
Using **cy.origin()** when I use the command Cypress.require() with any path from a class or requiring some file it gives the user the error bellow:

```
cy.origin() failed to run the callback function due to the following error:

Processing the origin callback errored:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

    at new NodeError (node:internal/errors:405:5)

    at validateString (node:internal/validators:162:11)

    at Object.dirname (node:path:654:5)

    at addTypeScriptConfig (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\node_modules@cypress\webpack-batteries-included-preprocessor\index.js:30:64)

    at preprocessor.getFullWebpackOptions (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\node_modules@cypress\webpack-batteries-included-preprocessor\index.js:189:12)

    at Object.processCallback [as handler] (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\child\cross_origin.js:16:26)

    at invoke (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\child\run_plugins.js:183:18)

    at C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\util.js:59:14

    at tryCatcher (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules\bluebird\js\release\util.js:16:23)

    at Function.Promise.attempt.Promise.try (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules\bluebird\js\release\method.js:39:29)

    at Object.wrapChildPromise (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\util.js:58:23)

    at RunPlugins.execute (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\child\run_plugins.js:164:21)

    at EventEmitter.<anonymous> (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\child\run_plugins.js:56:12)

    at EventEmitter.emit (node:events:517:28)

    at EventEmitter.emit (node:domain:489:12)

    at process.<anonymous> (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@packages\server\lib\plugins\util.js:33:22)

    at process.emit (node:events:517:28)

    at process.emit (node:domain:489:12)

    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\eduar\AppData\Local\Cypress\Cache\12.14.0\Cypress\resources\app\node_modules@cspotcode\source-map-support\source-map-support.js:745:40)

    at emit (node:internal/child_process:944:14)

    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The code I use for the step is:
```
import { When } from "@badeball/cypress-cucumber-preprocessor";

When('I test origin', () => {
    cy.origin('https://www.google.com', () => {
        const basePO = Cypress.require('../page_objects/basePO')
        basePO.getPageTitle()
    })
})
```

**Comment by badeball** [comment]
This can be reproduced by solely using `@bahmutov/cypress-esbuild-preprocessor` and not including this preprocessor, as seen [here](https://github.com/badeball/reproducible-issues/tree/master/cypress/Cypress.require). Thus, the issue lies elsewhere. You can try opening up an issue at either repositories.
