### ISSUE TITLE
Error running plugin

### ISSUE THREAD

**Issue by yesid-lopez** [badeball/cypress-cucumber-preprocessor#365]
Hello I'm trying to use cucumber with my cypress test. This is what I have:
```javascript
"cypress": "^4.4.1",
 "cypress-cucumber-preprocessor": "^2.3.1"
```
But when I try to execute the test I'm getting this error:

![image](https://user-images.githubusercontent.com/35767777/79825101-b29c3400-835d-11ea-87af-d8e9631ff1c9.png)

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/ylopezs/git/splunk/swft/cypress/plugins/index.js`)

**Details:** Error: Cannot find module 'coffeescript'
Require stack:
- /Users/ylopezs/git/splunk/swft/node_modules/coffeeify/index.js
- /Users/ylopezs/git/splunk/swft/node_modules/module-deps/index.js
- /Users/ylopezs/git/splunk/swft/node_modules/browserify/index.js
- /Users/ylopezs/git/splunk/swft/node_modules/@cypress/browserify-preprocessor/index.js
- /Users/ylopezs/git/splunk/swft/node_modules/cypress-cucumber-preprocessor/lib/index.js
- /Users/ylopezs/git/splunk/swft/cypress/plugins/index.js
- /Users/ylopezs/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/ylopezs/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ylopezs/git/splunk/swft/node_modules/coffeeify/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at nr (/Users/ylopezs/git/splunk/swft/node_modules/module-deps/index.js:302:21)
    at onfile (/Users/ylopezs/git/splunk/swft/node_modules/resolve/lib/async.js:106:21)
    at onex (/Users/ylopezs/git/splunk/swft/node_modules/resolve/lib/async.js:161:32)
    at /Users/ylopezs/git/splunk/swft/node_modules/resolve/lib/async.js:11:20
    at callback (/Users/ylopezs/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:159:5)

**Stack trace:**
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/ylopezs/git/splunk/swft/cypress/plugins/index.js`)
    at Object.get (/Users/ylopezs/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:348:11)
    at EventEmitter.handleError (/Users/ylopezs/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:136:20)
    at EventEmitter.emit (events.js:210:5)
    at ChildProcess.<anonymous> (/Users/ylopezs/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by lgandecki** [comment]
Hello. Sorry to hear you have problem using our plugins.
We are happy to help. Any chance for a simple standalone reproduction? That would also help you to narrow down the source of the possible problem

**Comment by smrtyviks** [comment]
I am also facing same issue, was there any update to this issue or any resolution?

**Comment by lgandecki** [comment]
Unfortunately not, please make a small reproduction and push to GitHub.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
