### ISSUE TITLE
Not able to run the Cypress tests in run mode

### ISSUE THREAD

**Issue by smrtyviks87** [badeball/cypress-cucumber-preprocessor#444]
### Current behavior

run command: node_modules\.bin\cypress run --spec **/*.feature

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.2.0                                                                              │
  │ Browser:    Electron 80 (headless)                                                             │
  │ Specs:      3 found (ChangeBillSettings.feature, Indbetaling.feature, test.feature)            │
  │ Searched:   **\*.feature                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  ChangeBillSettings.feature                                                      (1 of 3)
"[object Object]" reporter blew up with error:
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Module.require (internal/modules/cjs/loader.js:846:3)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Mocha.reporter (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:167:21)
    at new Mocha (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:88:8)
    at Reporter.setRunnables (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\reporter.js:191:20)
    at Object.onSetRunnables (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\project.js:348:20)
    at Socket.<anonymous> (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\socket.js:300:17)
    at Socket.emit (events.js:210:5)
    at C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Error: invalid reporter "[object Object]"
    at Mocha.reporter (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:180:13)
    at new Mocha (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:88:8)
    at Reporter.setRunnables (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\reporter.js:191:20)
    at Object.onSetRunnables (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\project.js:348:20)
    at Socket.<anonymous> (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\socket.js:300:17)
    at Socket.emit (events.js:210:5)
    at C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Error: invalid reporter "[object Object]"
    at Mocha.reporter (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:180:13)
    at new Mocha (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\mocha\lib\mocha.js:88:8)
    at Reporter.setRunnables (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\reporter.js:191:20)
    at Object.onSetRunnables (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\project.js:348:20)
    at Socket.<anonymous> (C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\socket.js:300:17)
    at Socket.emit (events.js:210:5)
    at C:\Users\UserXXX\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\socket\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

### Desired behavior
Cypress tests with .feature file should run

### Test code to reproduce
**Index.js**

let percyHealthCheck = require('@percy/cypress/task')
const cucumber = require('cypress-cucumber-preprocessor').default
const chokidar = require('chokidar');
module.exports = (on, config) => {
    on("task", percyHealthCheck);
    on('file:preprocessor', cucumber())
};

Cypress .json:
{
  "viewportWidth": 1000,
  "viewportHeight": 1000,
  "defaultCommandTimeout":30000,
  "video": true,
  "testFiles": "**/*.{feature,features}",
  "reporter": "cucumber-html-reporter",
  "reporterOptions": {
    "reporterEnabled":"mochawesome",
    "mochawesomeReporterOptions":{
    "reportDir": "cypress/cucumber-json",
    "overwrite": false,
    "html": false,
    "json": true
  }
  }

} 
Package.json:

 "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "step_definitions": "cypress/support/Step_Definitions",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },

### Versions

* **Cypress version**: 4.2.0
* **Preprocessor version**:2.3.0
* **Node version**:12.18.3

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
