### ISSUE TITLE
Error running plugin: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed

### ISSUE THREAD

**Issue by dipika654** [badeball/cypress-cucumber-preprocessor#585]
Getting this issue while working with Cypress- cucumber preprocessor

Message: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (C:\Users\AJ\CypressAutomation\cypress\plugins\index.js)

Details:

TypeError: Cannot destructure property 'name' of '(intermediate value).parse(...).feature' as it is undefined.
    at module.exports (C:\Users\AJ\CypressAutomation\node_modules\cypress-cucumber-preprocessor\lib\loader.js:29:11)
    at Stream.end (C:\Users\AJ\CypressAutomation\node_modules\cypress-cucumber-preprocessor\lib\index.js:24:18)
    at _end (C:\Users\AJ\CypressAutomation\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\AJ\CypressAutomation\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Users\AJ\CypressAutomation\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28)
    at DestroyableTransform.emit (events.js:327:22)
    at endReadableNT (C:\Users\AJ\CypressAutomation\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Stack trace:

Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Users\AJ\CypressAutomation\cypress\plugins\index.js`)
    at Object.get (C:\Users\AJ\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\errors.js:988:15)
    at EventEmitter.handleError (C:\Users\AJ\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\plugins\index.js:175:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\AJ\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Package.json:

  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^7.5.0",
    "cypress-cucumber-preprocessor": "^4.1.2",
    "cypress-xpath": "^1.6.2"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
index.js

const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}

**Comment by DevGabrielDeSouza** [comment]
Same problem here...

**Comment by baotqnttifi** [comment]
same issue

**Comment by baotqnttifi** [comment]
I found the reason , because I have unimplemented feature step.
Now when i remove them and it works

**Comment by ASuhail8** [comment]
Same issue.

**Comment by ASuhail8** [comment]
I got it fixed.
I noticed that the issue is in the feature file, it was just identifying the Feature and Scenario keywords.
So i deleted and just typed Feature and let the intellisense complete my word.

i ran the feature file and it worked.

![Before](https://user-images.githubusercontent.com/29089766/131875673-39637f86-de0f-4654-8cdc-ad1764882c5f.PNG)
![after](https://user-images.githubusercontent.com/29089766/131875676-7cca8be3-038a-40e4-9aa0-cade3400c9b4.PNG)

**Comment by alajoao** [comment]
> Eu consertei. Percebi que o problema está no arquivo do recurso, não estava identificando as palavras-chave do **recurso** e do **cenário** . Então eu apaguei e apenas digitei Feature e deixei o intellisense completar minha palavra.
> 
> Eu executei o arquivo de recurso e funcionou.
> 
> ![Antes](https://user-images.githubusercontent.com/29089766/131875673-39637f86-de0f-4654-8cdc-ad1764882c5f.PNG) ![depois de](https://user-images.githubusercontent.com/29089766/131875676-7cca8be3-038a-40e4-9aa0-cade3400c9b4.PNG)

Muito obrigado mano! Salvou minha vida

**Comment by FgrDesarrollo** [comment]
Change in your file .feature   `Scenario : ` for `Scenario Outline: ` and run !!

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by anilpujaraofficial** [comment]
![Capture](https://user-images.githubusercontent.com/65593381/174522830-857216f2-097e-4113-a2dc-25fdc8f568fe.PNG)
@all

**Comment by badeball** [comment]
@anilpujaraofficial, read through [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
