### ISSUE TITLE
Can't run existing Cypress browserify scripts with latest badeball preprocessor version

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#709]
### Current behavior

I Previously used Cypress Cucumber preprocessor with browserify. Now, I have upgraded to badeball/cypress-cucumber-preprocessor - version "^9.1.3". After upgrading I can't execute my existing scripts in run mode.

### ERROR THROWN:

An error was thrown in your plugins file while executing the handler for the before:run event.

The error we received was:

TypeError: fs_1.promises.rm is not a function
    at Object.handler (C:\Users\Documents\GitHub\New-Omnichannel\node_modules\@badeball\cypress-cucumber-preprocessor\lib\add-cucumber-preprocessor-plugin.js:49:29)
    at invoke (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:22:16)
    at C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\util.js:45:14
    at tryCatcher (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at Object.wrapChildPromise (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\util.js:44:23)
    at wrapChildPromise (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:116:10)
    at execute (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:129:14)
    at EventEmitter.<anonymous> (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:213:5)
    at EventEmitter.emit (events.js:314:20)
    at process.<anonymous> (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at process.emit (events.js:314:20)
    at process.emit (C:\Users\AppData\Local\Cypress\Cache\9.6.0\Cypress\resources\app\node_modules\source-map-support\source-map-support.js:495:21)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run test-local" terminated with exit code: 1.

### Desired behavior

After upgrading to latest package, existing scripts should work!

### Test code to reproduce

MY PLUGIN FILE:

/**
 * @type {Cypress.PluginConfig}
 */
import { preprocessor } from "@badeball/cypress-cucumber-preprocessor/browserify";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
const fs = require('fs');
const loadAsh = require('lodash');
const path = require('path');
const browserify = require('@cypress/browserify-preprocessor');
export default async (on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions) => {
	on("file:preprocessor",
		preprocessor(config, {
			...browserify.defaultOptions,
			typescript: require.resolve("typescript"),
		})
	);
	on('task', {
		consoleLog(message: string) {
			console.log(message);
			return null;
		},
		copyFile({ fromDirectory, toDirectory }: { fromDirectory: string, toDirectory: string }) {
			const from: string = path.join(process.cwd(), fromDirectory);
			const to: string = path.join(process.cwd(), toDirectory);
			fs.copyFile(from, to, (err: any) => {
				if (err) throw err;
				return null;
			});
			return null;
		}
	});
	// @ts-ignore
	on('after:spec', (spec, results) => {
		if (results && results.video) {
			const failures = loadAsh.some(results.tests, (test: any) => {
				return loadAsh.some(test.attempts, { state: 'failed' });
			});
			if (!failures) {
				fs.unlink(results.video, (err: any) => {
					if (err) {
						console.error(err);
						return;
					};
				});
			};
		};
	});
	await addCucumberPreprocessorPlugin(on, config);
	return config;
};

My Dependencies:
"dependencies": {
		"@badeball/cypress-cucumber-preprocessor": "^9.1.3",
		"@cypress/browserify-preprocessor": "^3.0.2",
		"@types/adm-zip": "^0.5.0",
		"@types/dateformat": "^5.0.0",
		"@types/edit-json-file": "^1.7.0",
		"@types/fs-extra": "^9.0.13",
		"@types/node-fetch": "^2.6.1",
		"adm-zip": "^0.5.9",
		"ansi-colors": "^4.1.1",
		"browserstack-cypress-cli": "^1.14.0",
		"cypress": "^9.6.0",
		"cypress-iframe": "^1.0.1",
		"cypress-plugin-tab": "^1.0.5",
		"cypress-xpath": "^1.6.2",
		"dateformat": "^4.6.3",
		"edit-json-file": "^1.7.0",
		"execa": "^4.0.1",
		"fakerator": "^0.3.5",
		"fs": "^0.0.1-security",
		"fs-extra": "^10.0.1",
		"http-server": "^14.1.0",
		"make-dir": "^3.1.0",
		"multiple-cucumber-html-reporter": "^1.20.0",
		"node-fetch": "^2.6.7",
		"nodejs-file-downloader": "^4.9.3",
		"resolve": "^1.22.0",
		"ts-node": "^10.7.0",
		"typescript": "^4.6.4",
                 "del": "^6.0.0",
		"lodash": "^4.17.21"
	}

### Versions

* **Cypress version**: 9.6.0
* **Preprocessor version**:9.1.3
* **Node version**:12.22.0

**Comment by badeball** [comment]
Upgrade node to at least v14.14.0, ref. https://nodejs.org/api/fs.html#fspromisesrmpath-options.
