### ISSUE TITLE
TypeError: cucumber is not a function

### ISSUE THREAD

**Issue by NullPiotrException** [badeball/cypress-cucumber-preprocessor#710]
### Current behavior

After switching to @badeball/cypress-cucumber-preprocessor I get this error when running `cypress open`:
```
An unexpected error occurred
The function exported by the plugins file threw an error.

We invoked the function exported by .../cypress-cucumber-testing/cypress/plugins/index.js, but it threw an error.

TypeError: cucumber is not a function    at module.exports (.../cypress-cucumber-testing/cypress/plugins/index.js:22:29)
    at .../.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:90:12
    at tryCatcher (.../.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (.../.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (.../.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:87:7)
    at EventEmitter.<anonymous> (.../.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:198:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (.../.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Desired behavior

`cypress open` without errors.

### Test code to reproduce

1. `git clone https://github.com/peterszeles/cypress-cucumber-testing`
2. `cd cypress-cucumber-testing`
3. In `package.json` change `"cypress-cucumber-preprocessor": "^4.0.1",` to `"@badeball/cypress-cucumber-preprocessor": "^9.1.3",`.
4. In `cypress/plugins/index.js` change `const cucumber = require('cypress-cucumber-preprocessor').default` to `const cucumber = require('@badeball/cypress-cucumber-preprocessor').default`.
5. `./node_modules/.bin/cypress open`

### Versions

* **Cypress version**: 9.6.1 (9.6.1 is from my project; in the example it's 7.3.0)
* **Preprocessor version**: 9.1.3
* **Node version**: 8.5.5

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md#configuration
