### ISSUE TITLE
configFile is invalid: Cannot find module 'esbuild'

### ISSUE THREAD

**Issue by bartonhammond** [badeball/cypress-cucumber-preprocessor#765]
### Current behavior
I am upgrading to this project (from original 4.3) and to cypress 10 at same time
I've searched Stackoverflow for answers
I've read guide to upgrading to version 11
I've read guide to upgrading to Cypress 10

I've `rm -rf node_modules`
updated `package.json` and `cypress.config.js`
and then
`npm install` 
and then 
`npx cypress open`

```
Error: Cannot find module 'esbuild'
Require stack:
- C:\Users\hammonbu\git\smc-cypress\node_modules\@bahmutov\cypress-esbuild-preprocessor\src\index.js
- C:\Users\hammonbu\git\smc-cypress\cypress.config.js
- C:\Users\hammonbu\AppData\Local\Cypress\Cache\10.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js
- C:\Users\hammonbu\AppData\Local\Cypress\Cache\10.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\require_async_child.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object. (C:\Users\hammonbu\git\smc-cypress\node_modules\@bahmutov\cypress-esbuild-preprocessor\src\index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object. (C:\Users\hammonbu\git\smc-cypress\cypress.config.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadFile (C:\Users\hammonbu\AppData\Local\Cypress\Cache\10.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter. (C:\Users\hammonbu\AppData\Local\Cypress\Cache\10.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
    at EventEmitter.emit (events.js:315:20)
    at process. (C:\Users\hammonbu\AppData\Local\Cypress\Cache\10.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
```

cypress.config.js
```
const { defineConfig } = require('cypress')
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");

async function setupNodeEvents(on, config) {
    await preprocessor.addCucumberPreprocessorPlugin(on, config);

    on(
        "file:preprocessor",
        createBundler({
            plugins: [createEsbuildPlugin.default(config)],
        })
    );

    // Make sure to return the config object as it might have been modified by the plugin.
    return config;
}

module.exports = defineConfig({
    e2e: {
        specPattern: "**/*.feature",
        supportFile: "cypress/support/index.js",
        setupNodeEvents
    }
})
```

package.json
```
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^11.5.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",
    "cypress": "^10.3.0"
  }
```
### Versions

* **Cypress version**:  11.5.0
* **Preprocessor version**: 2.1.3
* **Node version**:  v14.16.0

### Checklist

- [Y] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [Y] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [Y] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
`esbuild` is an optional peer dependency which you need to install yourself if you want to use `esbuild` as a bundler, IE. run `npm i --save esbuild`.

**Comment by bartonhammond** [comment]
@badeball Um - ok - didn't know that - thanks
