### ISSUE TITLE
Cannot read properties of undefined (reading 'seconds') error during execution

### ISSUE THREAD

**Issue by kiran-epic** [badeball/cypress-cucumber-preprocessor#787]
### Current behavior

I am receiving the following error when executing my tests since today. At this time, I won't be able to put the project on a repo for you to reproduce, but I can help get you any logs if you need so.

**Error**
![image](https://user-images.githubusercontent.com/98785077/182493621-9afd076a-d849-4f5c-8dbc-997ae6f08f76.png)

**Stack Trace**
`at duration ([node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:56:1](https://webstaging4.storymagic.co/__/#))
    at Context.eval ([node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:395:1](https://webstaging4.storymagic.co/__/#))
From previous event:
    at Context.thenFn (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:153485:64)
    at Context.then (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:153937:22)
    at Context.<anonymous> (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:171678:20)
    at <unknown> (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:170365:16)
From previous event:
    at CommandQueue.runCommand (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:170344:18)
    at next (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:170496:20)
From previous event:
    at next (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:170496:40)
    at next (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:170462:17)
    at <unknown> (https://webstaging4.storymagic.co/__cypress/runner/cypress_runner.js:170525:17)`

### Versions

* **Cypress version**: 10.3.0
* **Preprocessor version**: 12.0.0
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
No reproducible example = no bueno, this should be pretty clear by now. I can't fix a problem I can't see.

**Comment by kiran-epic** [comment]
@badeball Here you go https://github.com/kiran-epic/CypressCucumber_ExceptionWithAwait 

I was able to find the root cause of the issue. Happens when you use await keyword under certain circumstances. 

Let me know if you need additional information

**Comment by badeball** [comment]
Using async/await isn't supported in Cypress, period. You shouldn't use it at all. There's some heuristic implemented to track this and warn you, but it's flaky at best. You can see that your example (last test), yields different results in run-mode and open-mode.
