### ISSUE TITLE
Doc string after data table throws compile error

### ISSUE THREAD

**Issue by simon-ittmann** [badeball/cypress-cucumber-preprocessor#825]
### Current behavior

A doc string after a data table is throwing an error:

    **Then** do something
      | Name           |  Age | 
      | Sepp            |   39   | 
    """
    Comment
    """

```
Error: Webpack Compilation Error
Module build failed (from ../node_modules/@badeball/cypress-cucumber-preprocessor/webpack.js):
Error: (24:5): expected: #EOF, #TableRow, #StepLine, #TagLine, #ExamplesLine, #ScenarioLine, #RuleLine, #Comment, #Empty, got '"""'
    at Watching.handle [as handler] (C:\Users\test\e2e-tests\node_modules\@cypress\webpack-preprocessor\dist\index.js:180:23)
    at C:\Users\test\e2e-tests\node_modules\webpack\lib\Watching.js:290:9
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\e2e-tests\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Watching._done (C:\Users\test\e2e-tests\node_modules\webpack\lib\Watching.js:287:28)
    at C:\Users\test\e2e-tests\node_modules\webpack\lib\Watching.js:209:21
    at Compiler.emitRecords (C:\Users\test\e2e-tests\node_modules\webpack\lib\Compiler.js:919:5)
    at C:\Users\test\e2e-tests\node_modules\webpack\lib\Watching.js:187:22
    at C:\Users\test\e2e-tests\node_modules\webpack\lib\Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\e2e-tests\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\Users\test\e2e-tests\node_modules\webpack\lib\Compiler.js:882:27
    at C:\Users\test\e2e-tests\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\test\e2e-tests\node_modules\neo-async\async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\e2e-tests\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\Users\test\e2e-tests\node_modules\webpack\lib\Compiler.js:736:33
    at C:\Users\test\e2e-tests\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\test\AppData\Local\Cypress\Cache\10.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\test\AppData\Local\Cypress\Cache\10.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\graceful-fs.js:143:16
    at C:\Users\test\AppData\Local\Cypress\Cache\10.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\gaceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:201:23)
```

### Desired behavior

No compile error

### Test code to reproduce

-

### Versions

* **Cypress version**: 10
* **Preprocessor version**: 12.1.0
* **Node version**: 18

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Not a bug, that's just how it is.
