### ISSUE TITLE
When setting "type": "module" in package.json, cypress throws an error

### ISSUE THREAD

**Issue by goldeneye5671** [badeball/cypress-cucumber-preprocessor#841]
### Current behavior

When trying to run cypress-cucumber-preprocessor with the package.json file including "type": "module" I get an error stating that "exports is not defined in ES module scope"

### Desired behavior

I should be able to run cypress with cypress-cucumber-preprocessor with the package.json file including "type": "module" without any errors

### Test code to reproduce

1. Clone the repository: `https://github.com/goldeneye5671/ccp-issue.git` and run npm install
2. Launch cypress with npx cypress open
3. Cypress will then throw an error stating that "exports is not defined in ES module scope"

This is the only log I was able to get from cypress:

```
Your configFile is invalid: ./ccp-issue/cypress.config.ts

It threw an error when required, check the stack trace below:

ReferenceError: exports is not defined in ES module scope
    at file://ccp-issue/cypress.config.ts:14:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async loadFile (/Users/user1/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter.<anonymous> (/Users/user1/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:32)
```

notice that if "type": "module" is removed that cypress no longer throws the error

### Versions

* **Cypress version**: 10.8.0
* **Preprocessor version**: 13.0.1
* **Node version**: 18.7.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

Let me know if there are any problems with replication or for more information

**Comment by badeball** [comment]
This isn't related to preprocessing, you have this issue whether you use `cypress-cucumber-preprocessor` or not. You need to instruct TS to output the expected type.

```json
{
  "compilerOptions": {
    "module": "es6"
  }
}
```

**Comment by goldeneye5671** [comment]
I'm not so sure about that, as even setting that as the compilerOptions, I am still unable to get past errors either stating that it can't find the plugin:
```
file:///Users/user/Projects/ccp-issue/cypress.config.ts:38
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'addCucumberPreprocessorPlugin' not found. The requested module '@badeball/cypress-cucumber-preprocessor' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@badeball/cypress-cucumber-preprocessor';
const { addCucumberPreprocessorPlugin } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async loadFile (/Users/user/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter.<anonymous> (/Users/user/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:32)
```
or when that change is made
```
the error was thrown while executing your e2e.setupNodeEvents() function:

ReferenceError: require is not defined
    at file:///Users/user/Projects/ccp-issue/cypress.config.ts:19:19
    at step (file:///Users/user/Projects/ccp-issue/cypress.config.ts:32:23)
    at Object.next (file:///Users/user/Projects/ccp-issue/cypress.config.ts:13:53)
    at fulfilled (file:///Users/user/Projects/ccp-issue/cypress.config.ts:4:58)
```

**Comment by badeball** [comment]
Again, not an issue with the preprocessor. If you want node in module-mode, then `require.resolve` (in your cypress.config.ts) won't be available. See eg. https://stackoverflow.com/questions/54977743/do-require-resolve-for-es-modules.

**Comment by loki-tailor** [comment]
@goldeneye5671 - you can refer to this as well. => https://stackoverflow.com/a/60225870/7415499
