### ISSUE TITLE
Unable to run tests in Gitlab CI with Cypress 9.x

### ISSUE THREAD

**Issue by karthikr89** [badeball/cypress-cucumber-preprocessor#846]
The current framework setup I use is - 
Cypress 9.6.0
Cucumber
preprocessor

I am able to run the tests on local without any issues.
Getting the following error message when trying to run the tests in Gitlab CI - 

The error was:
Error: Build failed with 1 error:
node_modules/@badeball/cypress-configuration/lib/cypress-configuration/cypress-pre10-configuration.js:195:42: ERROR: [plugin: feature] [testFiles].flat is not a function
    at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1624:15)
    at runOnEndCallbacks (/app/node_modules/esbuild/lib/main.js:1266:28)
    at runOnEndCallbacks (/app/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/app/node_modules/esbuild/lib/main.js:1264:7)
    at sendRequest (/app/node_modules/esbuild/lib/main.js:1377:14)
    at responseCallbacks.set (/app/node_modules/esbuild/lib/main.js:678:9)
    at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/app/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
- A missing file or dependency
- A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.

I also mentioned testFiles: [ "**/*.feature" ] in cypress.json

<img width="1127" alt="Screenshot 2022-09-27 at 15 55 03" src="https://user-images.githubusercontent.com/4947373/192546078-c8909741-2e9b-4a84-b881-dcb7452d5b0e.png">

**Comment by badeball** [comment]
You have to use node v11.0.0 or higher.

**Comment by karthikr89** [comment]
@badeball you mean in the CI machines? if so, we are using version 16.x and my local machine uses node 17.x
