### ISSUE TITLE
Cy.origin causes TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by kiran-epic** [badeball/cypress-cucumber-preprocessor#854]
### Current behavior

Using cy.origin causes the exception `(uncaught exception)TypeError: Failed to construct 'URL': Invalid URL` And when using cy.origin in `beforeEach()` hook, the subsequent tests don't run due to this error. Here is the console error 

```
index.bf30ee46.js:99332 TypeError: The following error originated from your test code, not from Cypress.

  > Failed to construct 'URL': Invalid URL

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Because this error occurred during a `before each` hook we are skipping all of the remaining tests.
    at Context.eval (cypress/support/e2e.js:20:7)
From previous event:
    at CommandQueue.run (https://google.com/__cypress/runner/cypress_runner.js:171640:21)
    at CommandQueue.run (https://google.com/__cypress/runner/cypress_runner.js:156283:15)
    at $Cy.runQueue (https://google.com/__cypress/runner/cypress_runner.js:157333:14)
    at cy.<computed> [as origin] (https://google.com/__cypress/runner/cypress_runner.js:157442:12)
    at __stackReplacementMarker (https://google.com/__cypress/runner/cypress_runner.js:156789:13)
    at runnable.fn (https://google.com/__cypress/runner/cypress_runner.js:157625:19)
    at callFn (https://google.com/__cypress/runner/cypress_runner.js:107910:21)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://google.com/__cypress/runner/cypress_runner.js:107897:7)
    at https://google.com/__cypress/runner/cypress_runner.js:164934:30
From previous event:
    at Object.onRunnableRun (https://google.com/__cypress/runner/cypress_runner.js:164919:53)
    at $Cypress.action (https://google.com/__cypress/runner/cypress_runner.js:153707:28)
    at Runnable.run (https://google.com/__cypress/runner/cypress_runner.js:162582:13)
    at next (https://google.com/__cypress/runner/cypress_runner.js:108412:10)
    at https://google.com/__cypress/runner/cypress_runner.js:108456:5
    at timeslice (https://google.com/__cypress/runner/cypress_runner.js:102382:27)
```

### Desired behavior

cy.origin shouldn't cause any errors.

### Test code to reproduce

https://github.com/kiran-epic/CypressCucumber_Origin

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**: 13.0.2
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> cy.origin shouldn't cause any errors.

While this might be true that it shouldn't, it doesn't appear to be related to preprocessing at all. Cypress' own issue tracker is more appropriate.

**Comment by kiran-epic** [comment]
@badeball The issue only occurs when using the cucumber preprocessor, if I write the tests using mocha describe {} blocks, there is no such issue.

**Comment by badeball** [comment]
In that case I need to see a complete example illustrating what you're referring to, similar to what you provided above, just without the preprocessor.

**Comment by kiran-epic** [comment]
https://github.com/kiran-epic/Cypress_Vanilla

**Comment by kiran-epic** [comment]
nvm. Cypress [v10.10.0](https://docs.cypress.io/guides/references/changelog#10-10-0) fixes the issue!
