### ISSUE TITLE
Reusing Cypress Steps

### ISSUE THREAD

**Issue by javjim** [badeball/cypress-cucumber-preprocessor#858]
### Current behavior

I have created some PageObjects like this:

```
 export default class searchGuestPage {
  static getFirstName = () => cy.get('#firstName');
  static getLastName = () => cy.get('#lastName');
}
```

### Desired behavior

and I want to be able to reuse steps instead of creating one for each of the fields

Feature file definition:
```
    Then I set 'searchGuest' field 'FirstName' to 'AB'
```

common.ts 
```
import searchGuestPage from '../../e2e/pages/searchGuestsPage';


Then('I set {string} field {string} to {string}', (page: string, locator: string, value: string) => {
   // searchGuestPage.getFirstName().type(value);  <- This WORKS

  // eslint-disable-next-line no-eval
  eval(`${page}Page.get${locator}().type('${value}');`);
  );
```

This produces a Reference Error : searchGuestPage is not defined.

Full Error:

```
index.b2772887.js:99332 ReferenceError: searchGuestPage is not defined
    at eval (http://localhost:3000/__cypress/tests?p=cypress\e2e\navigation.feature)
    at Context.eval (cypress/support/step_definitions/common.ts:105:5)
From previous event:
    at Context.thenFn (http://localhost:3000/__cypress/runner/cypress_runner.js:139099:63)
    at Context.then (http://localhost:3000/__cypress/runner/cypress_runner.js:139521:21)
    at wrapped (http://localhost:3000/__cypress/runner/cypress_runner.js:157367:19)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:156095:15)
From previous event:
    at CommandQueue.runCommand (http://localhost:3000/__cypress/runner/cypress_runner.js:156073:8)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:156220:19)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:156249:16)
From previous event:
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:156220:39)
From previous event:
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:171645:77)
From previous event:
    at CommandQueue.run (http://localhost:3000/__cypress/runner/cypress_runner.js:171640:21)
    at CommandQueue.run (http://localhost:3000/__cypress/runner/cypress_runner.js:156283:15)
    at $Cy.runQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:157333:14)
    at cy.<computed> [as then] (http://localhost:3000/__cypress/runner/cypress_runner.js:157442:12)
    at runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:157625:19)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:107910:21)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:107897:7)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:164934:30)
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:164919:53)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:153707:28)
    at Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:162582:13)
    at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:108569:10)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:108695:12)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:108478:14)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:108488:7)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:108390:14)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:108456:5)
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:102382:27)
```

### Versions

* **Cypress version**: 10.9.0 
* **Preprocessor version**: 12.0.1
* **Node version**:

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Stop cross-posting and debug your own damn code.
