### ISSUE TITLE
Webpack/TS example does not run.

### ISSUE THREAD

**Issue by LewisCraik** [badeball/cypress-cucumber-preprocessor#861]
### Current behavior

Webpack/TS example does not run.

Stack trace:
```
Error: Cannot find module 'webpack'
Require stack:
- /Users/lewiscraik/Developer/cypress-cucumber-preprocessor/examples/webpack-ts/node_modules/@cypress/webpack-preprocessor/dist/index.js
- /Users/lewiscraik/Developer/cypress-cucumber-preprocessor/examples/webpack-ts/cypress.config.ts
- /Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js
- /Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object. (/Users/lewiscraik/Developer/cypress-cucumber-preprocessor/examples/webpack-ts/node_modules/@cypress/webpack-preprocessor/dist/index.js:32:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions. [as .js] (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object. (/Users/lewiscraik/Developer/cypress-cucumber-preprocessor/examples/webpack-ts/cypress.config.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions. [as .ts] (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at loadFile (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter. (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (events.js:400:28)
    at EventEmitter.emit (domain.js:475:12)
    at process. (/Users/lewiscraik/Library/Caches/Cypress/10.10.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (events.js:400:28)
```

### Desired behavior

The example should work

### Test code to reproduce

1. Cloned repo
2. Changed to examples/webpack-ts folder
3. `yarn install`
4. `yarn cypress open`

### Versions

* **Cypress version**: 10.10
* **Preprocessor version**: 13.0.2
* **Node version**: 14.19

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Fixed with 512d0ccd68e7044459e227749da7640787bdc8a7.
