### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'UNKNOWN') after update to v12.0.0

### ISSUE THREAD

**Issue by nikepol** [badeball/cypress-cucumber-preprocessor#932]
### Current behavior

There is an issue after updating to the last version of cypress-cucumber-preprocessor, it happens after cucumber-preprocessor updating to 12.0.0 or higher. Everything works with 11.5.1
```
Your configFile is invalid: /Users/user/project/e2e-cypress/cypress.config.js

It threw an error when required, check the stack trace below:

node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/gherkin/src/pickles/compile.ts:5:31
  3 | 
  4 | const pickleStepTypeFromKeyword: { [key in messages.StepKeywordType]: messages.PickleStepType } = {
> 5 |     [messages.StepKeywordType.UNKNOWN]: messages.PickleStepType.UNKNOWN,
    |                               ^
  6 |     [messages.StepKeywordType.CONTEXT]: messages.PickleStepType.CONTEXT,
  7 |     [messages.StepKeywordType.ACTION]: messages.PickleStepType.ACTION,
  8 |     [messages.StepKeywordType.OUTCOME]: messages.PickleStepType.OUTCOME,
  9 |     [messages.StepKeywordType.CONJUNCTION]: null
```

```
TypeError: Cannot read properties of undefined (reading 'UNKNOWN')
    at Object. (/Users/user/project/e2e-cypress/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/gherkin/src/pickles/compile.ts:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions. [as .js] (/Users/user/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:851:20)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/Users/user/project/e2e-cypress/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/gherkin/src/generateMessages.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions. [as .js] (/Users/user/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:851:20)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/Users/user/project/e2e-cypress/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/gherkin/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions. [as .js] (/Users/user/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:851:20)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
```

**cypress.config.js**

```
const { defineConfig } = require('cypress');
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");





module.exports = defineConfig({
  fixturesFolder: 'cypress/fixtures',
  screenshotsFolder: 'cypress/screenshots',
  videosFolder: 'cypress/videos',
  projectId: 'e2e',
  viewportWidth: 1400,
  viewportHeight: 660,
  videoCompression: 0,
  defaultCommandTimeout: 20000,
  requestTimeout: 20000,

  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.)
    experimentalStudio: true,
    experimentalSessionAndOrigin: true,
    experimentalWebKitSupport: true,
    async setupNodeEvents(on, config) {
      await preprocessor.addCucumberPreprocessorPlugin(on, config);
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin.default(config)],
        })
      );
        }
      });

      on('file:preprocessor', bundler);
      await addCucumberPreprocessorPlugin(on, config);
      return config;
    },

    excludeSpecPattern: 'cypress/e2e/cucumber/**/*.cy.{js,ts}',
    specPattern: [
      'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}',
      'cypress/e2e/**/*.feature'
    ]
  }
});
```
### Desired behavior

I want to update cypress-cucumber-preprocessor and make it work
### Versions

* **11.2.0**:
* **15.1.2**:
* **v18**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).
<img width="959" alt="Screenshot 2023-01-25 at 10 27 17" src="https://user-images.githubusercontent.com/2943574/214527277-bb4fba63-30b4-401e-840c-568f82c28e2d.png">

**Comment by nikepol** [comment]
fixing cypress.config.js according to https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples fixed this error
